services:
  web:
    image: docker.xuanyuan.me/vulhub/mongo-express:0.53.0
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  mongo:
    image:  docker.xuanyuan.me/library/mongo:3.4
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./mongod.conf:/etc/mongod.conf
