version: '2'
services:
 web:
    image: docker.1ms.run/vulhub/pgadmin:7.6
    ports:
      - "5050:5050"
    volumes:
      - ./data:/var/lib/pgadmin/storage
 db:
    image: docker.xuanyuan.me/library/postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cve
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_statement=mod"
      - "-c"
      - "log_line_prefix=%n [%r] [%p] "
      - "-c"
      - "max_connections=4000"