version: '2'
services:
 web:
   build: .
   ports:
    - "8080:8080"
    - "5005:5005"
   environment:
      # USE_POSTGRES: "true"
      LD_LIBRARY_PATH: "/hook/lib"
      LD_PRELOAD: "/hook/lib/libquicklog.so"
   volumes:
    - ./data:/usr/src/apache-ofbiz/runtime/uploads
#  postgres:
#   image: docker.xuanyuan.me/library/postgres:9.6-alpine
#   ports:
#     - "5432:5432"
#   environment:
#     - POSTGRES_PASSWORD=ofbiz
#     - POSTGRES_USER=ofbiz
#     - POSTGRES_DB=ofbiz
#   command:
#     - "postgres"
#     - "-c"
#     - "log_destination=stderr"
#     - "-c"
#     - "log_statement=mod"
#     - "-c"
#     - "log_line_prefix=%n [%r] [%p] "
#     - "-c"
#     - "max_connections=4000"
