services:
    db:
        image: docker.xuanyuan.me/library/postgres:17.4-alpine
        environment:
            POSTGRES_DB: dev
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: devpassword
            TZ: "Asia/Shanghai"
            PGTZ: "Asia/Shanghai"
        volumes:
            - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
        ports:
            - 5432:5432
        command:
            - "postgres"
            - "-c"
            - "log_destination=stderr"
            - "-c"
            - "log_statement=mod"
            - "-c"
            - "log_line_prefix=%n [%r] [%p] "

    web:
        build: .
        environment:
            DATABASE_URL: postgresql://dev:devpassword@db:5432/dev
            LD_PRELOAD: /app/hook_glibc.so
        depends_on:
            - db
        volumes:
            # - .:/app
            - ./data:/app/log
        command: >
            /bin/sh -c 'pipenv run hypercorn main:app --reload --bind 0.0.0.0:8000 --workers 8 --access-logfile -'
        ports:
            - 8000:8000
