version: '2'
services:
  web:
    image: vulhub/cmsms:2.2.9.1
    ports:
     - "80:80"
    volumes:
     - ./data:/var/www/html/uploads
    depends_on:
     - db
  db:
   image: mysql:5.7.32
   ports:
     - "3306:3306"
   volumes:
    - ./logs:/var/log/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cmsms
   command: 
    - --general-log=1 
    - --log-output=FILE
    - --general-log-file=/var/log/mysql/mysql.log
