version: '2'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - ./src:/usr/src
    - ./data:/usr/data
    depends_on:
    - db
  db:
    image: docker.xuanyuan.me/library/postgres:9.6-alpine
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=cve
    ports:
    - "5432:5432"
    command:
    - "postgres"
    - "-c"
    - "log_destination=stderr"
    - "-c"
    - "log_statement=mod"
    - "-c"
    - "log_line_prefix=%n [%r] [%p] "
