version: '2'
services:
 web:
   image: vulhub/joomla:3.7.0
   depends_on:
    - mysql
   environment: 
    - JOOMLA_DB_HOST=mysql
    - JOOMLA_DB_PORT=3306
    - JOOMLA_DB_USER=root
    - JOOMLA_DB_PASSWORD=vulhub
    - JOOMLA_DB_NAME=joomla
   ports:
    - "8080:80"
   volumes:
    - ./data:/var/www/html/images/data
 mysql:
   image: mysql:5.7
   environment: 
    - MYSQL_ROOT_PASSWORD=vulhub
   ports:
    - "3306:3306"
   volumes:
    - ./log:/var/log/mysql
   command: 
    - --general-log=1 
    - --log-output=FILE
    - --general-log-file=/var/log/mysql/mysql.log
    - --sql-mode=NO_ENGINE_SUBSTITUTION
