version: '3'
services:
 web:
   image: vulhub/geoserver:2.23.2
   depends_on:
    - postgres
   ports:
    - "8080:8080"
   volumes:
     - ./startup.sh:/startup.sh
     - ./hook:/hook
     - ./data:/mnt/geoserver/data_dir
   environment:
      LD_LIBRARY_PATH: "/hook/lib"
      LD_PRELOAD: "/hook/lib/libquicklog.so"
      JAVA_TOOL_OPTIONS: "-javaagent:/hook/agent/java-agent.jar"
   command: bash /startup.sh
 postgres:
   image: docker.xuanyuan.me/postgis/postgis:14-3.3-alpine
   ports:
    - "5432:5432"
   environment: 
    - POSTGRES_PASSWORD=vulhub
    - POSTGRES_DB=geoserver
   command:
    - "postgres"
    - "-c"
    - "log_destination=stderr"
    - "-c"
    - "log_statement=mod"
    - "-c"
    - "log_line_prefix=%n [%r] [%p] "
    - "-c"
    - "max_connections=4000"
